repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.2
    hooks:
      - id: golangci-lint
        args: ["--config=ci/linters/.golangci.yml"]
#      - id: golangci-lint-full
#        args: ["--config=ci/linters/.golangci.yml"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: check-added-large-files
