name: "Go project CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Install python 3.13.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.x'
      - name: Init linters
        run: |
          make init_linters
      - name: Run linters
        run: |
          make lint

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: template_db_test
          POSTGRES_USER: template_user
          POSTGRES_PASSWORD: template_password
    env:
      POSTGRES_DB: template_db_test
      POSTGRES_USER: template_user
      POSTGRES_PASSWORD: template_password
      DATABASE_URL: "postgres://template_user:template_password@localhost:5432/template_db_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Run tests
        run: |
          make go_all_tests

  # build docker container
  # push them to registry
  # deploy them to k8s???
